// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNkY-kJxAkta-GpiMEDv-5elEApGyI01s',
    appId: '1:773586464375:web:df7287069c74f797916072',
    messagingSenderId: '773586464375',
    projectId: 'sleeper-38655',
    authDomain: 'sleeper-38655.firebaseapp.com',
    storageBucket: 'sleeper-38655.appspot.com',
    measurementId: 'G-S3DEHDQ0VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb-Bzcaq-RuuwMkUu2yqm_dk9CZ2zPfbI',
    appId: '1:773586464375:android:a3b0468c5ff1e262916072',
    messagingSenderId: '773586464375',
    projectId: 'sleeper-38655',
    storageBucket: 'sleeper-38655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ0_3yJ9sUsN_H0gyxo3OqKB7siDjOAQI',
    appId: '1:773586464375:ios:c91e53af8a7ea50b916072',
    messagingSenderId: '773586464375',
    projectId: 'sleeper-38655',
    storageBucket: 'sleeper-38655.appspot.com',
    androidClientId: '773586464375-1vfhtol9h33hun4a3c5j9adi42iq9c1e.apps.googleusercontent.com',
    iosClientId: '773586464375-b1fo0sed0q5ctc39pofiichlq5so6ngo.apps.googleusercontent.com',
    iosBundleId: 'com.lim1t.sleeper',
  );
}
